In [1]:
using DelimitedFiles

Load .txt datafile with following columns: 
body_number (n), initial time of transit (tt0), actual transit times (tt), measurement error (sigtt)

In [2]:
# Example file
data_file = readdlm("INPUTS/tt_30.0sEMB30.0yrs.txt",Float64)

80×4 Array{Float64,2}:
 1.0  2.4335e6   2.4335e6   0.000347222
 1.0  2.43373e6  2.43373e6  0.000347222
 1.0  2.43395e6  2.43395e6  0.000347222
 1.0  2.43418e6  2.43418e6  0.000347222
 1.0  2.4344e6   2.4344e6   0.000347222
 1.0  2.43463e6  2.43463e6  0.000347222
 1.0  2.43485e6  2.43485e6  0.000347222
 1.0  2.43508e6  2.43508e6  0.000347222
 1.0  2.4353e6   2.4353e6   0.000347222
 1.0  2.43553e6  2.43553e6  0.000347222
 1.0  2.43575e6  2.43575e6  0.000347222
 1.0  2.43598e6  2.43598e6  0.000347222
 1.0  2.4362e6   2.4362e6   0.000347222
 ⋮                                     
 2.0  2.44056e6  2.44056e6  0.000347222
 2.0  2.44093e6  2.44093e6  0.000347222
 2.0  2.44129e6  2.44129e6  0.000347222
 2.0  2.44166e6  2.44166e6  0.000347222
 2.0  2.44203e6  2.44203e6  0.000347222
 2.0  2.44239e6  2.44239e6  0.000347222
 2.0  2.44276e6  2.44276e6  0.000347222
 2.0  2.44312e6  2.44312e6  0.000347222
 2.0  2.44349e6  2.44349e6  0.000347222
 2.0  2.44385e6  2.44385e6  0.000347222
 2.0  2.44422e6  

NB: code assumes that planet 1 is labelled 1 and planet 2 is labeled 2. the number of transit times is sum of rows with that label.

In [10]:
# Do a 2 planet fit, given a jmax integer value
include("fit_planet2.jl") 

fit_planet2 (generic function with 3 methods)

### without reference t0

In [11]:
@time fit_planet2(data_file, 5, 0.0, 1e-5)

[2.4335037654852555e6, 224.70077409577533]
1.3135433825266147e-8
[2.433624402638408e6, 365.2564266571264]
8.682191471190402e-11
Initial parameters: [3.0e-6, 224.70077409577533, 2.4335037654852555e6, 0.01, 0.01, 3.0e-6, 365.2564266571264, 2.433624402638408e6, 0.01, 0.01]
Initial chi-square: 812.3590456907988
Finished 2-planet fit: [2.647523303887924e-6, 224.70077626828143, 2.433503765488956e6, 0.002578811344086398, 0.010378328486752, 3.06449639023031e-6, 365.2564294664862, 2.4336244026185255e6, 0.01588865786247525, 0.009693381753353264] 29
New 2-planet chi-square: 585.5675125529058
Output file in Fitfromdatafile.jld2
  1.884048 seconds (2.22 M allocations: 115.287 MiB, 2.10% gc time)


### with reference t0

In [12]:
@time fit_planet2(data_file, 5, 2430000, 1e-5)

[3503.7654852567784, 224.70077409575646]
9.172523094539269e-16
[3624.4026384093218, 365.25642665702384]
3.355873101703838e-14
Initial parameters: [3.0e-6, 224.70077409575646, 3503.7654852567784, 0.01, 0.01, 3.0e-6, 365.25642665702384, 3624.4026384093218, 0.01, 0.01]
Initial chi-square: 812.3590569057454
Finished 2-planet fit: [2.9380153697129402e-6, 224.70077831626037, 3503.765429099878, 0.03081019305418419, 0.011457500858907978, 3.2595689949612584e-6, 365.25643295059126, 3624.402560434307, 0.038440262285722275, 0.010409974573520126] 2
New 2-planet chi-square: 582.8973442491646
Output file in Fitfromdatafile.jld2
  0.570554 seconds (858.28 k allocations: 40.525 MiB)


from Venus + Earth data

In [26]:
EVdata_file = readdlm("INPUTS/tt_30.0snoEMB30.0yrs.txt",Float64)

80×4 Array{Float64,2}:
 1.0  2.4335e6   2.4335e6   0.000347222
 1.0  2.43373e6  2.43373e6  0.000347222
 1.0  2.43395e6  2.43395e6  0.000347222
 1.0  2.43418e6  2.43418e6  0.000347222
 1.0  2.4344e6   2.4344e6   0.000347222
 1.0  2.43463e6  2.43463e6  0.000347222
 1.0  2.43485e6  2.43485e6  0.000347222
 1.0  2.43508e6  2.43508e6  0.000347222
 1.0  2.4353e6   2.4353e6   0.000347222
 1.0  2.43553e6  2.43553e6  0.000347222
 1.0  2.43575e6  2.43575e6  0.000347222
 1.0  2.43598e6  2.43598e6  0.000347222
 1.0  2.4362e6   2.4362e6   0.000347222
 ⋮                                     
 2.0  2.44056e6  2.44056e6  0.000347222
 2.0  2.44093e6  2.44093e6  0.000347222
 2.0  2.44129e6  2.44129e6  0.000347222
 2.0  2.44166e6  2.44166e6  0.000347222
 2.0  2.44203e6  2.44203e6  0.000347222
 2.0  2.44239e6  2.44239e6  0.000347222
 2.0  2.44276e6  2.44276e6  0.000347222
 2.0  2.44312e6  2.44312e6  0.000347222
 2.0  2.44349e6  2.44349e6  0.000347222
 2.0  2.44385e6  2.44385e6  0.000347222
 2.0  2.44422e6  

### without reference t0

In [14]:
@time fit_planet2(EVdata_file, 5, 0.0, 1e-5)

[2.4335038532321756e6, 224.70030244576117]
2.5404363185319427e-9
[2.4336244853840605e6, 365.2577282914466]
9.129537088439601e-10
Initial parameters: [3.0e-6, 224.70030244576117, 2.4335038532321756e6, 0.01, 0.01, 3.0e-6, 365.2577282914466, 2.4336244853840605e6, 0.01, 0.01]
Initial chi-square: 2.716503269010148e7
Finished 2-planet fit: [-3.3004978522901815e-6, 224.7002043573421, 2.4335038541247873e6, 0.8798346351100548, 0.03910533652620045, 7.345041144357513e-6, 365.25771547220285, 2.4336244847786454e6, 0.8552007515124023, -0.12473551192665419] 6608
New 2-planet chi-square: 2.69225504814796e7
Output file in Fitfromdatafile.jld2
 51.595160 seconds (4.99 M allocations: 2.016 GiB, 0.54% gc time)


### with reference t0

In [15]:
@time fit_planet2(EVdata_file, 5, 2430000, 1e-5)

[3503.8532321729535, 224.70030244585558]
6.252297268669018e-15
[3624.4853840606884, 365.25772829145905]
1.1498149658538231e-14
Initial parameters: [3.0e-6, 224.70030244585558, 3503.8532321729535, 0.01, 0.01, 3.0e-6, 365.25772829145905, 3624.4853840606884, 0.01, 0.01]
Initial chi-square: 2.7165032689376578e7
Finished 2-planet fit: [-3.1479972618256325e-6, 224.7002033410568, 3503.8541397009603, 0.9434504530003683, 0.07593675947080761, 7.090174518438679e-6, 365.2577159157465, 3624.4847919316367, 0.9197385240387567, -0.08916848208698598] 2
New 2-planet chi-square: 2.6922437476042956e7
Output file in Fitfromdatafile.jld2
  0.199994 seconds (21.22 k allocations: 7.530 MiB)


In [27]:
nt1 = sum(EVdata_file[:,1] .== 1.0)

49

In [28]:
nt2 = sum(EVdata_file[:,1] .== 2.0)

31

In [30]:
tref=0.0
tt1 = vec(EVdata_file[1:nt1,3]) .- tref
tt2 = vec(EVdata_file[nt1+1:nt1+nt2,3]) .- tref
sigtt1 = EVdata_file[1:nt1,4]
sigtt2 = EVdata_file[nt1+1:nt1+nt2,4]

31-element Array{Float64,1}:
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 ⋮                     
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224
 0.00034722222222222224

In [36]:
  function find_coeffs(tt,period,sigtt)
    nt = length(tt)
    x = zeros(2,nt)
    x[1,1:nt] .= 1.0
    x[2,1] = 0.0 
    for i=2:nt
      x[2,i] = x[2,i-1] + round((tt[i]-tt[i-1])/period) 
    end
    coeff,covcoeff = regress(x,tt,sigtt)
    # println(tt,sigtt,std(sigtt))
    println(coeff)
    println(sum((tt .- coeff[1].-coeff[2].*x[2,:])./sigtt).^2)
    return coeff,covcoeff
  end
  # Guess the planets' period by finding median of transit times
  p1_est = median(tt1[2:end] - tt1[1:end-1])
  p2_est = median(tt2[2:end] - tt2[1:end-1])
  # Do fit to find linear ephemeris (t0, per)
  coeff1,covcoeff1 = find_coeffs(tt1,p1_est,sigtt1)
  coeff2,covcoeff2 = find_coeffs(tt2,p2_est,sigtt2)
  t01 = coeff1[1]; per1 = coeff1[2]
  t02 = coeff2[1]; per2 = coeff2[2]
  t1  = collect(t01 .+ per1 .* range(0,stop=nt1-1,length=nt1)) 
  t2  = collect(t02 .+ per2 .* range(0,stop=nt2-1,length=nt2))
  # Best-fit linear transit times:
  tt0 = [t1;t2]
  # Actual transit times:
  tt=[tt1;tt2]
  sigtt=[sigtt1;sigtt2] 
  weight = ones(nt1+nt2)./ sigtt.^2 #assigns each data point stat weight d.t. noise = 1/σ^2

  # Okay,now let's do a 2-planet fit:
  # param_names = mass ratio,period,initial transit time,e*cos(omega),e*sin(omega)
  init_param = [3e-6,per1,t01,0.01,0.01,
                3e-6,per2,t02,0.01,0.01] 
  println("Initial parameters: ",init_param)

[2.4335038532321756e6, 224.70030244576117]
2.5404363185319427e-9
[2.4336244853840605e6, 365.2577282914466]
9.129537088439601e-10
Initial parameters: [3.0e-6, 224.70030244576117, 2.4335038532321756e6, 0.01, 0.01, 3.0e-6, 365.2577282914466, 2.4336244853840605e6, 0.01, 0.01]


In [42]:
  ntrans = [nt1,nt2]

2-element Array{Int64,1}:
 49
 31

In [50]:
n1,n2=ntrans[1:2]
n1

49

In [47]:
include("TTVFaster/src/ttv_wrapper.jl")  
chisq = 0.0  #check memory allocation >>>>>>>>>>>>
  # println(params,tt[1],sigtt[1])
  tt_model = ttv_wrapper(tt0,2,ntrans,init_param,5,false) #,fixp3,p3_cur)
  for j=1:length(tt)
    chisq += (tt[j]-tt_model[j])^2/sigtt[j]^2
  end

In [48]:
chisq

1.4772477637816468e21